language: python
python:
  - "3.6"
  - "3.7-dev"

  # command to install dependencies
install:
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install codecov

# command to run tests
script:
  - pytest --cov -v

after_success:
  - codecov